steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/debate-app",
        "--build-arg",
        "VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY",
        "--build-arg",
        "VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN",
        "--build-arg",
        "VITE_FIREBASE_PROJECT_ID=$_VITE_FIREBASE_PROJECT_ID",
        "--build-arg",
        "VITE_FIREBASE_STORAGE_BUCKET=$_VITE_FIREBASE_STORAGE_BUCKET",
        "--build-arg",
        "VITE_FIREBASE_MESSAGING_SENDER_ID=$_VITE_FIREBASE_MESSAGING_SENDER_ID",
        "--build-arg",
        "VITE_FIREBASE_APP_ID=$_VITE_FIREBASE_APP_ID",
        "--build-arg",
        "VITE_GEMINI_API_KEY=$_VITE_GEMINI_API_KEY",
        ".",
      ]
images:
  - "gcr.io/$PROJECT_ID/debate-app"
